# Generated by Django 6.1 on 2026-08-18 20:19

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('descripcion', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='actividades/')),
                ('publicada', models.BooleanField(default=True, help_text='Desmarca para ocultarla del sitio sin borrarla')),
            ],
            options={
                'verbose_name': 'Actividad diaria',
                'verbose_name_plural': 'Actividades diarias',
                'ordering': ['-fecha'],
            },
        ),
    ]
