# Generated by Django 6.1 on 2026-08-18 22:30

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanaActividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Selecciona el día lunes de la semana que corresponde.', unique=True)),
                ('publicada', models.BooleanField(default=True, help_text='Desmarca para ocultarla del sitio sin borrarla')),
                ('lunes_descripcion', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Lunes')),
                ('lunes_imagen', models.ImageField(blank=True, null=True, upload_to='actividades/', verbose_name='Imagen del lunes')),
                ('martes_descripcion', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Martes')),
                ('martes_imagen', models.ImageField(blank=True, null=True, upload_to='actividades/', verbose_name='Imagen del martes')),
                ('miercoles_descripcion', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Miércoles')),
                ('miercoles_imagen', models.ImageField(blank=True, null=True, upload_to='actividades/', verbose_name='Imagen del miércoles')),
                ('jueves_descripcion', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Jueves')),
                ('jueves_imagen', models.ImageField(blank=True, null=True, upload_to='actividades/', verbose_name='Imagen del jueves')),
                ('viernes_descripcion', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Viernes')),
                ('viernes_imagen', models.ImageField(blank=True, null=True, upload_to='actividades/', verbose_name='Imagen del viernes')),
            ],
            options={
                'verbose_name': 'Semana de actividades',
                'verbose_name_plural': 'Semanas de actividades',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
    ]
