# Generated by Django 6.1 on 2026-08-19 17:18

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_paginaactividades'),
    ]

    operations = [
        migrations.AddField(
            model_name='semanaactividades',
            name='descripcion_general',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Resumen o presentación general de las actividades de la semana (opcional).', verbose_name='Descripción general de la semana'),
        ),
    ]
