# Generated by Django 6.1 on 2026-08-18 20:19

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_jardin', models.CharField(default='Jardín Infantil Mi Pequeño Mundo', max_length=150)),
                ('lema', models.CharField(blank=True, help_text='Ej: Convivir en armonía, aprender con alegría', max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('whatsapp_url', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sitio/')),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
        migrations.CreateModel(
            name='PaginaInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_hero', models.CharField(default='Bienvenidos a Mi Pequeño Mundo', max_length=200)),
                ('subtitulo_hero', models.CharField(blank=True, max_length=250)),
                ('imagen_hero', models.ImageField(blank=True, null=True, upload_to='inicio/')),
                ('texto_bienvenida', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
            ],
            options={
                'verbose_name': 'Página de inicio',
                'verbose_name_plural': 'Página de inicio',
            },
        ),
        migrations.CreateModel(
            name='Reglamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('archivo_pdf', models.FileField(blank=True, help_text='Opcional: versión descargable en PDF', null=True, upload_to='reglamento/')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reglamento interno',
                'verbose_name_plural': 'Reglamento interno',
            },
        ),
    ]
