# Generated by Django 6.1 on 2026-08-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglamento',
            name='imagen_hero',
            field=models.ImageField(blank=True, null=True, upload_to='reglamento/'),
        ),
    ]
