# Generated by Django 6.1 on 2026-08-19 17:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reglamento_imagen_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaSobreNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_hero', models.ImageField(blank=True, null=True, upload_to='sobre-nosotros/')),
                ('bienvenida', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='<p>Reciban un afectuoso saludo de bienvenida. Agradecemos la confianza que han depositado en nuestro jardín: tengan la seguridad de que en <strong>Mi Pequeño Mundo</strong> sus hijos e hijas encontrarán un espacio seguro para crecer en armonía y aprender con alegría, con nuestro amor y dedicación.</p><p>Para muchas familias es un lugar nuevo. De a poco, día a día, los niños y niñas irán adquiriendo confianza y seguridad, descubriendo un mundo especial de risas, compañeritos, juegos, cantos y colores — también algunos desencuentros que sabremos acompañar como mediadores, para compartir en sana convivencia.</p><p>Los invitamos a mantener una comunicación constante, basada en el respeto y la comprensión mutuos, y a vivir día a día el clima familiar y cercano que esperamos para nuestra comunidad escolar. Ya son parte de la gran familia Mi Pequeño Mundo.</p>', verbose_name='Mensaje de bienvenida')),
                ('mision', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='<p>Ser un jardín infantil que se compromete con la educación integral y de calidad de sus niños y niñas, poniendo énfasis en el desarrollo de las diversas áreas de la educación parvularia, con un enfoque de altas expectativas, en un ambiente de sana convivencia, ecológico e inclusivo, donde se respeta la diversidad, de modo que sepan adaptarse con armonía a los cambios de su entorno, proyectándose a una vida futura a través de experiencias significativas en los procesos educativos.</p>', verbose_name='Misión')),
                ('vision', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='<p>En nuestro jardín infantil pretendemos que los alumnos y alumnas, al finalizar su proceso educativo, alcancen los objetivos de aprendizaje que les permitan insertarse exitosamente en el ámbito escolar, convirtiéndose en ciudadanos insertos y participativos, con valores permanentes de respeto a sí mismos, su entorno social y el medio ambiente.</p>', verbose_name='Visión')),
                ('sellos_educativos', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='<h3>Aprender a vivir en armonía</h3><p>Lograr un equilibrio en los pensamientos, acciones y sentimientos de los niños y niñas, para que disfruten cada momento del proceso de enseñanza-aprendizaje, desarrollando habilidades blandas que faciliten su interacción con el entorno y generando en toda la comunidad escolar un clima de sana convivencia, respetuosa, asertiva y afectuosa.</p><h3>Educar para la vida, formando agentes de cambio</h3><p>Educar en los niños y niñas las habilidades para adaptarse con flexibilidad a los cambios permanentes de su entorno, de manera que apliquen sus experiencias y aprendizajes para lograr una inserción escolar y social exitosa.</p><h3>Experiencias significativas</h3><p>Entregar a cada niño y niña vivencias y experiencias pedagógicas de conocimientos y habilidades con un sentido real para el desarrollo de su vida integral, siempre en la búsqueda de una educación inclusiva, integradora y de calidad.</p>', verbose_name='Sellos educativos')),
                ('valores_intro', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='<p>El sustento de nuestros valores institucionales son los valores humanistas, basados en el respeto del ser humano y de este con su entorno social: un ser libre, capaz de reconocer sus fortalezas y debilidades y de ver lo mismo en quienes lo rodean. Estos valores guían a toda nuestra comunidad escolar.</p>', verbose_name='Introducción a valores y competencias')),
                ('lista_valores', models.TextField(blank=True, default='Dignidad, Autonomía, Diversidad, Responsabilidad, Templanza, Creatividad, Libertad, Respeto, Empatía, Alegría, Verdad, Honestidad, Bondad, Gratitud, Justicia, Cooperación, Solidaridad', help_text='Lista de valores separados por coma. Se muestran como etiquetas en la página.', verbose_name='Valores institucionales')),
            ],
            options={
                'verbose_name': 'Página Sobre Nosotros',
                'verbose_name_plural': 'Página Sobre Nosotros',
            },
        ),
    ]
