# Generated by Django 6.1 on 2026-08-25 19:04

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_paginasobrenosotros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('archivo', models.FileField(help_text='Solo se permiten archivos PDF.', upload_to='documentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('orden', models.PositiveIntegerField(default=0, help_text='Los documentos con número menor aparecen primero')),
                ('subido_el', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['orden', '-subido_el'],
            },
        ),
        migrations.AlterModelOptions(
            name='reglamento',
            options={'verbose_name': 'Página de Documentos', 'verbose_name_plural': 'Página de Documentos'},
        ),
        migrations.RemoveField(
            model_name='reglamento',
            name='archivo_pdf',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='blog_url',
            field=models.URLField(blank=True, default='https://mipequenomundo2011.blogspot.com/', help_text='Se muestra como sección y enlace en el sitio. Déjalo vacío para ocultarlo.', verbose_name='Enlace del blog'),
        ),
        migrations.AlterField(
            model_name='reglamento',
            name='contenido',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Texto opcional que se muestra sobre la lista de documentos.', verbose_name='Texto introductorio'),
        ),
    ]
