# Generated by Django 6.1 on 2026-08-19 01:58

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, help_text='Déjalo vacío si es un evento de un solo día. Complétalo si abarca varios días (por ejemplo, una semana completa).', null=True)),
                ('descripcion', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='calendario/')),
                ('publicado', models.BooleanField(default=True, help_text='Desmarca para ocultarlo del sitio sin borrarlo')),
            ],
            options={
                'verbose_name': 'Evento del calendario',
                'verbose_name_plural': 'Eventos del calendario',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
