# Generated by Django 6.1 on 2026-08-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_hero', models.ImageField(blank=True, null=True, upload_to='calendario/')),
            ],
            options={
                'verbose_name': 'Portada de calendario',
                'verbose_name_plural': 'Portada de calendario',
            },
        ),
    ]
