# Generated by Django 6.1 on 2026-08-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_paginacalendario'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocalendario',
            name='hora_fin',
            field=models.TimeField(blank=True, help_text='Opcional. Hora en que termina la actividad, por ejemplo 13:00.', null=True),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='hora_inicio',
            field=models.TimeField(blank=True, help_text='Opcional. Hora en que comienza la actividad, por ejemplo 09:00.', null=True),
        ),
    ]
