# Generated by Django 6.1 on 2026-08-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FotoGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150)),
                ('imagen', models.ImageField(upload_to='galeria/')),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Las fotos con número menor aparecen primero')),
                ('subida_el', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foto de galería',
                'verbose_name_plural': 'Fotos de galería',
                'ordering': ['orden', '-subida_el'],
            },
        ),
    ]
