# Generated by Django 6.1 on 2026-08-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_paginagaleria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotogaleria',
            name='video_url',
            field=models.URLField(blank=True, help_text='Si se completa, la tarjeta enlaza directo a este video de YouTube en vez de abrir la foto en grande.', verbose_name='Enlace de YouTube'),
        ),
        migrations.AlterField(
            model_name='fotogaleria',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Para un video de YouTube puedes dejarla vacía: se usará la miniatura del video.', null=True, upload_to='galeria/'),
        ),
    ]
